Adding a very basic test for the `dumpurls` command.
This currently fails because `djangae.contrib.security.commands_utils.simplify_regex` dies with `AttributeError: 'module' object has no attribute 'views'`