Fix incorrect list of lists deduplication.
* in Python sets require all items to be hashable and in Python
immutable ones are hashable. Lists are mutable, so we got
TypeError: unhashable type: 'list' error
* we map list to tuples, deduplicate with set and map back to list